apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: bitnami/wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: my-mariadb-mariadb.default.svc.cluster.local:3306
        - name: WORDPRESS_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: WORDPRESS_DATABASE_USER
        - name: WORDPRESS_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: WORDPRESS_DATABASE_PASSWORD
        - name: WORDPRESS_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: wordpress-db-secret
              key: WORDPRESS_DATABASE_NAME